version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b $(go env GOPATH)/bin v1.23.8
      - run: go get -u github.com/golang/protobuf/protoc-gen-go
      - run: go get -u google.golang.org/grpc
      - run: go get -u github.com/shurcooL/vfsgen/cmd/vfsgendev
      - run: make format
      - run: make
      - run: make golangci-lint
      - run: make GO_PARALLEL="-p 1" test
      - run:
          name: Codecov report
          command: bash <(curl -s https://codecov.io/bash)
